project:
  type: website
  output-dir: docs

website:
  description: "Alyssa Cox Senior Project"
  site-url: https://coxabc.github.io/senior_proj/ # you must change this appropriately for RSS feeds to work properly
  title: "Alyssa Cox Senior Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/coxabc
      - icon: linkedin
        href: https://www.linkedin.com/in/alyssa-b-cox/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



